[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
# Redirect old HTML routes to homepage
[[redirects]]
  from = "/portfolio.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/"
  status = 301

# API function redirect
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
